//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Возраст.
    /// </summary>
    // *** Start programmer edit section *** (Возраст CustomAttributes)

    // *** End programmer edit section *** (Возраст CustomAttributes)
    public enum Возраст
    {
        
        // *** Start programmer edit section *** (Возраст.До35л CustomAttributes)

        // *** End programmer edit section *** (Возраст.До35л CustomAttributes)
        [Caption("до 35 л.")]
        До35л,
        
        // *** Start programmer edit section *** (Возраст.От35 CustomAttributes)

        // *** End programmer edit section *** (Возраст.От35 CustomAttributes)
        [Caption("от 35 до 45 л.")]
        От35,
        
        // *** Start programmer edit section *** (Возраст.От45 CustomAttributes)

        // *** End programmer edit section *** (Возраст.От45 CustomAttributes)
        [Caption("от 45 до 55 л.")]
        От45,
        
        // *** Start programmer edit section *** (Возраст.От55 CustomAttributes)

        // *** End programmer edit section *** (Возраст.От55 CustomAttributes)
        [Caption("от 55 л. и старше")]
        От55,
    }
}
