//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Инф из анкет.
    /// </summary>
    // *** Start programmer edit section *** (ИнфИзАнкет CustomAttributes)

    // *** End programmer edit section *** (ИнфИзАнкет CustomAttributes)
    [AutoAltered()]
    [Caption("Информация из анкет")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИнфИзАнкетE", new string[] {
            "Анкеты as \'Номер анкеты\'",
            "Анкеты.ДатаЗаполн as \'Дата заполнения анкеты\'",
            "Анкеты.ГлавнПричин as \'Причина увольнения\'",
            "Анкеты.ПолУволСотр as \'Пол\'",
            "Анкеты.ОтносКатСотр as \'Категория\'",
            "Анкеты.ВозрастСотруд as \'Возраст\'"})]
    [MasterViewDefineAttribute("ИнфИзАнкетE", "Анкеты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ИнфИзАнкетL", new string[] {
            "Анкеты as \'Номер анкеты\'",
            "Анкеты.ДатаЗаполн as \'Дата заполнения анкеты\'",
            "Анкеты.ГлавнПричин as \'Причина увольнения\'",
            "Анкеты.ПолУволСотр as \'Пол\'",
            "Анкеты.ОтносКатСотр as \'Категория\'",
            "Анкеты.ВозрастСотруд as \'Возраст\'"})]
    [MasterViewDefineAttribute("ИнфИзАнкетL", "Анкеты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class ИнфИзАнкет : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Sektor_podbora_i_razvitiya_personala.Специалист fСпециалист;
        
        private IIS.Sektor_podbora_i_razvitiya_personala.Анкеты fАнкеты;
        
        // *** Start programmer edit section *** (ИнфИзАнкет CustomMembers)

        // *** End programmer edit section *** (ИнфИзАнкет CustomMembers)

        
        /// <summary>
        /// Инф из анкет.
        /// </summary>
        // *** Start programmer edit section *** (ИнфИзАнкет.Анкеты CustomAttributes)

        // *** End programmer edit section *** (ИнфИзАнкет.Анкеты CustomAttributes)
        [PropertyStorage(new string[] {
                "Анкеты"})]
        public virtual IIS.Sektor_podbora_i_razvitiya_personala.Анкеты Анкеты
        {
            get
            {
                // *** Start programmer edit section *** (ИнфИзАнкет.Анкеты Get start)

                // *** End programmer edit section *** (ИнфИзАнкет.Анкеты Get start)
                IIS.Sektor_podbora_i_razvitiya_personala.Анкеты result = this.fАнкеты;
                // *** Start programmer edit section *** (ИнфИзАнкет.Анкеты Get end)

                // *** End programmer edit section *** (ИнфИзАнкет.Анкеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнфИзАнкет.Анкеты Set start)

                // *** End programmer edit section *** (ИнфИзАнкет.Анкеты Set start)
                this.fАнкеты = value;
                // *** Start programmer edit section *** (ИнфИзАнкет.Анкеты Set end)

                // *** End programmer edit section *** (ИнфИзАнкет.Анкеты Set end)
            }
        }
        
        /// <summary>
        /// Инф из анкет.
        /// </summary>
        // *** Start programmer edit section *** (ИнфИзАнкет.Специалист CustomAttributes)

        // *** End programmer edit section *** (ИнфИзАнкет.Специалист CustomAttributes)
        [PropertyStorage(new string[] {
                "Специалист"})]
        public virtual IIS.Sektor_podbora_i_razvitiya_personala.Специалист Специалист
        {
            get
            {
                // *** Start programmer edit section *** (ИнфИзАнкет.Специалист Get start)

                // *** End programmer edit section *** (ИнфИзАнкет.Специалист Get start)
                IIS.Sektor_podbora_i_razvitiya_personala.Специалист result = this.fСпециалист;
                // *** Start programmer edit section *** (ИнфИзАнкет.Специалист Get end)

                // *** End programmer edit section *** (ИнфИзАнкет.Специалист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнфИзАнкет.Специалист Set start)

                // *** End programmer edit section *** (ИнфИзАнкет.Специалист Set start)
                this.fСпециалист = value;
                // *** Start programmer edit section *** (ИнфИзАнкет.Специалист Set end)

                // *** End programmer edit section *** (ИнфИзАнкет.Специалист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИнфИзАнкетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнфИзАнкетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнфИзАнкетE", typeof(IIS.Sektor_podbora_i_razvitiya_personala.ИнфИзАнкет));
                }
            }
            
            /// <summary>
            /// "ИнфИзАнкетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнфИзАнкетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнфИзАнкетL", typeof(IIS.Sektor_podbora_i_razvitiya_personala.ИнфИзАнкет));
                }
            }
        }
    }
}
