//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оценка.
    /// </summary>
    // *** Start programmer edit section *** (Оценка CustomAttributes)

    // *** End programmer edit section *** (Оценка CustomAttributes)
    public enum Оценка
    {
        
        // *** Start programmer edit section *** (Оценка.1 CustomAttributes)

        // *** End programmer edit section *** (Оценка.1 CustomAttributes)
        [Caption("1")]
        1,
        
        // *** Start programmer edit section *** (Оценка.2 CustomAttributes)

        // *** End programmer edit section *** (Оценка.2 CustomAttributes)
        [Caption("2")]
        2,
        
        // *** Start programmer edit section *** (Оценка.3 CustomAttributes)

        // *** End programmer edit section *** (Оценка.3 CustomAttributes)
        [Caption("3")]
        3,
        
        // *** Start programmer edit section *** (Оценка.4 CustomAttributes)

        // *** End programmer edit section *** (Оценка.4 CustomAttributes)
        [Caption("4")]
        4,
        
        // *** Start programmer edit section *** (Оценка.5 CustomAttributes)

        // *** End programmer edit section *** (Оценка.5 CustomAttributes)
        [Caption("5")]
        5,
        
        // *** Start programmer edit section *** (Оценка.6 CustomAttributes)

        // *** End programmer edit section *** (Оценка.6 CustomAttributes)
        [Caption("6")]
        6,
        
        // *** Start programmer edit section *** (Оценка.7 CustomAttributes)

        // *** End programmer edit section *** (Оценка.7 CustomAttributes)
        [Caption("7")]
        7,
        
        // *** Start programmer edit section *** (Оценка.8 CustomAttributes)

        // *** End programmer edit section *** (Оценка.8 CustomAttributes)
        [Caption("8")]
        8,
        
        // *** Start programmer edit section *** (Оценка.9 CustomAttributes)

        // *** End programmer edit section *** (Оценка.9 CustomAttributes)
        [Caption("9")]
        9,
        
        // *** Start programmer edit section *** (Оценка.10 CustomAttributes)

        // *** End programmer edit section *** (Оценка.10 CustomAttributes)
        [Caption("10")]
        10,
    }
}
