//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол.
    /// </summary>
    // *** Start programmer edit section *** (Пол CustomAttributes)

    // *** End programmer edit section *** (Пол CustomAttributes)
    public enum Пол
    {
        
        // *** Start programmer edit section *** (Пол.Ж CustomAttributes)

        // *** End programmer edit section *** (Пол.Ж CustomAttributes)
        [Caption("Женщина")]
        Ж,
        
        // *** Start programmer edit section *** (Пол.М CustomAttributes)

        // *** End programmer edit section *** (Пол.М CustomAttributes)
        [Caption("Мужчина")]
        М,
    }
}
