//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стаж.
    /// </summary>
    // *** Start programmer edit section *** (Стаж CustomAttributes)

    // *** End programmer edit section *** (Стаж CustomAttributes)
    public enum Стаж
    {
        
        // *** Start programmer edit section *** (Стаж.ДоГода CustomAttributes)

        // *** End programmer edit section *** (Стаж.ДоГода CustomAttributes)
        [Caption("до года")]
        ДоГода,
        
        // *** Start programmer edit section *** (Стаж.От1Года CustomAttributes)

        // *** End programmer edit section *** (Стаж.От1Года CustomAttributes)
        [Caption("от 1 года до 3-х л.")]
        От1Года,
        
        // *** Start programmer edit section *** (Стаж.От3 CustomAttributes)

        // *** End programmer edit section *** (Стаж.От3 CustomAttributes)
        [Caption("от 3-х до 5-ти л.")]
        От3,
        
        // *** Start programmer edit section *** (Стаж.От5 CustomAttributes)

        // *** End programmer edit section *** (Стаж.От5 CustomAttributes)
        [Caption("от 5-ти до 10-ти л.")]
        От5,
        
        // *** Start programmer edit section *** (Стаж.Более10 CustomAttributes)

        // *** End programmer edit section *** (Стаж.Более10 CustomAttributes)
        [Caption("более 10 л.")]
        Более10,
    }
}
