//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sektor_podbora_i_razvitiya_personala
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факторы.
    /// </summary>
    // *** Start programmer edit section *** (Факторы CustomAttributes)

    // *** End programmer edit section *** (Факторы CustomAttributes)
    public enum Факторы
    {
        
        // *** Start programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)
        [Caption("Взаимоотношения с коллегами")]
        ВзаимCКоллег,
        
        // *** Start programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)
        [Caption("Взаимоотношення с руководителем")]
        ВзаимСРуков,
        
        // *** Start programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)

        // *** End programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)
        [Caption("Санитарно-гигиенические условия")]
        СанитГигиеУсл,
        
        // *** Start programmer edit section *** (Факторы.СистЛьгот CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистЛьгот CustomAttributes)
        [Caption("Система льгот, компенсаций")]
        СистЛьгот,
        
        // *** Start programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)

        // *** End programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)
        [Caption("Снабжение необходимыми инструментами")]
        СнабНеобхИнст,
        
        // *** Start programmer edit section *** (Факторы.СистОфицПриз CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистОфицПриз CustomAttributes)
        [Caption("Система официального признания заслуг")]
        СистОфицПриз,
        
        // *** Start programmer edit section *** (Факторы.ИнтенРабот CustomAttributes)

        // *** End programmer edit section *** (Факторы.ИнтенРабот CustomAttributes)
        [Caption("Интенсивность работы")]
        ИнтенРабот,
        
        // *** Start programmer edit section *** (Факторы.ИнфСотруд CustomAttributes)

        // *** End programmer edit section *** (Факторы.ИнфСотруд CustomAttributes)
        [Caption("Информированность сотрудников")]
        ИнфСотруд,
        
        // *** Start programmer edit section *** (Факторы.ПерспКарРоста CustomAttributes)

        // *** End programmer edit section *** (Факторы.ПерспКарРоста CustomAttributes)
        [Caption("Перспективы карьерного роста")]
        ПерспКарРоста,
        
        // *** Start programmer edit section *** (Факторы.СистОбучения CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистОбучения CustomAttributes)
        [Caption("Система обучения и профессионального развития")]
        СистОбучения,
        
        // *** Start programmer edit section *** (Факторы.РазмЗарабПлат CustomAttributes)

        // *** End programmer edit section *** (Факторы.РазмЗарабПлат CustomAttributes)
        [Caption("Размер заработной платы")]
        РазмЗарабПлат,
        
        // *** Start programmer edit section *** (Факторы.СистАдаптации CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистАдаптации CustomAttributes)
        [Caption("Система адаптации и наставничества")]
        СистАдаптации,
        
        // *** Start programmer edit section *** (Факторы.Престижность CustomAttributes)

        // *** End programmer edit section *** (Факторы.Престижность CustomAttributes)
        [Caption("Престижность ПАО «Россети Сибирь»")]
        Престижность,
        
        // *** Start programmer edit section *** (Факторы.СодерРаботы CustomAttributes)

        // *** End programmer edit section *** (Факторы.СодерРаботы CustomAttributes)
        [Caption("Содержание работы")]
        СодерРаботы,
        
        // *** Start programmer edit section *** (Факторы.ОргРабПроцес CustomAttributes)

        // *** End programmer edit section *** (Факторы.ОргРабПроцес CustomAttributes)
        [Caption("Организация рабочего процесса")]
        ОргРабПроцес,
        
        // *** Start programmer edit section *** (Факторы.СистПремир CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистПремир CustomAttributes)
        [Caption("Система премирования")]
        СистПремир,
        
        // *** Start programmer edit section *** (Факторы.РезулРаботы CustomAttributes)

        // *** End programmer edit section *** (Факторы.РезулРаботы CustomAttributes)
        [Caption("Результаты работы")]
        РезулРаботы,
    }
}
